version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - webapp-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vue-frontend
    ports:
      - "80:80"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
